version: "3"

services:
  app:
    build: .
    environment:
      MONGO_URL: "mongodb://db:27017/test"
    depends_on:
      - db
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src
      - /usr/src/node_modules 
  db:
    image: mongo
    

